// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module idma_reg_obi (
        input wire clk,
        input wire arst_n,

        input wire obi_req,
        input wire [7:0] obi_addr,
        input wire obi_we,
        input wire [3:0] obi_be,
        input wire [31:0] obi_wdata,
        input wire [0:0] obi_aid,
        output logic obi_gnt,
        output logic obi_rvalid,
        output logic [31:0] obi_rdata,
        output logic [0:0] obi_rid,
        output logic obi_err,
        input wire obi_rready,

        input idma_reg_obi_pkg::idma_reg__in_t hwif_in,
        output idma_reg_obi_pkg::idma_reg__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [7:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // OBI Interface Implementation
    // This register block acts as an OBI subordinate

    localparam int unsigned DATA_WIDTH = idma_reg_obi_pkg::IDMA_REG_OBI_DATA_WIDTH;
    localparam int unsigned BYTES      = DATA_WIDTH/8;

    // State & holding regs
    logic is_active;            // A request is being served (not yet fully responded)
    logic gnt_q;                // one-cycle grant for A-channel
    logic rsp_pending;          // response ready but not yet accepted by manager
    logic [DATA_WIDTH-1:0] rsp_rdata_q;
    logic                      rsp_err_q;
    logic [$bits(obi_aid)-1:0] rid_q;

    // Latch AID on accept so we can echo it back with the response
    always_ff @(posedge clk or negedge arst_n) begin
      if (~arst_n) begin
        is_active      <= 1'b0;
        gnt_q          <= 1'b0;
        rsp_pending    <= 1'b0;
        rsp_rdata_q    <= '0;
        rsp_err_q      <= 1'b0;
        rid_q          <= '0;

        cpuif_req        <= '0;
        cpuif_req_is_wr  <= '0;
        cpuif_addr       <= '0;
        cpuif_wr_data    <= '0;
        cpuif_wr_biten   <= '0;
      end else begin
        // defaults
        cpuif_req <= 1'b0;
        gnt_q     <= obi_req & ~is_active;

        // Accept a new request when idle
        if (~is_active) begin
          if (obi_req) begin
            is_active       <= 1'b1;
            cpuif_req       <= 1'b1;
            cpuif_req_is_wr <= obi_we;
            cpuif_addr      <= obi_addr;
            cpuif_wr_data   <= obi_wdata;
            rid_q           <= obi_aid;
            // expand byte enables into bit mask
            for (int i = 0; i < BYTES; i++) begin
              cpuif_wr_biten[i*8 +: 8] <= {8{ obi_be[i] }};
            end
          end
        end

        // When the internal regblock finishes, capture the response
        if (is_active && (cpuif_rd_ack || cpuif_wr_ack)) begin
          rsp_pending <= 1'b1;
          rsp_rdata_q <= cpuif_rd_data;
          rsp_err_q   <= cpuif_rd_err | cpuif_wr_err;
          // NOTE: Keep 'is_active' asserted until the external R handshake completes
        end

        // Complete external R-channel handshake only when manager is ready
        if (rsp_pending && obi_rvalid && obi_rready) begin
          rsp_pending <= 1'b0;
          is_active   <= 1'b0; // free to accept the next request
        end
      end
    end

    // R-channel outputs (held stable while rsp_pending=1)
    assign obi_rvalid = rsp_pending;
    assign obi_rdata  = rsp_rdata_q;
    assign obi_err    = rsp_err_q;
    assign obi_rid    = rid_q;

    // A-channel grant (registered one-cycle pulse when we accept a request)
    assign obi_gnt = gnt_q;

    // If your OBI config disables RReady, tie it high in the top-level/TB; this logic still works.
    // If you want synthesis-time checking, you can add:
    // `ifndef SYNTHESIS
    //   initial begin
    //     if (0) $display("RReady supported; tie high if unused.");
    //   end
    // `endif

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic conf;
        logic status[16];
        logic next_id[16];
        logic done_id[16];
        logic dst_addr[1];
        logic src_addr[1];
        logic length[1];
        struct {
            logic dst_stride[1];
            logic src_stride[1];
            logic reps[1];
        } dim[1];
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_strb_is_external;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_external;
        is_external = '0;
        decoded_reg_strb.conf = cpuif_req_masked & (cpuif_addr == 8'h0);
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.status[i0] = cpuif_req_masked & (cpuif_addr == 8'h4 + (8)'(i0) * 8'h4);
            is_external |= cpuif_req_masked & (cpuif_addr == 8'h4 + (8)'(i0) * 8'h4);
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.next_id[i0] = cpuif_req_masked & (cpuif_addr == 8'h44 + (8)'(i0) * 8'h4);
            is_external |= cpuif_req_masked & (cpuif_addr == 8'h44 + (8)'(i0) * 8'h4);
        end
        for(int i0=0; i0<16; i0++) begin
            decoded_reg_strb.done_id[i0] = cpuif_req_masked & (cpuif_addr == 8'h84 + (8)'(i0) * 8'h4);
            is_external |= cpuif_req_masked & (cpuif_addr == 8'h84 + (8)'(i0) * 8'h4);
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.dst_addr[i0] = cpuif_req_masked & (cpuif_addr == 8'hd0 + (8)'(i0) * 8'h4);
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.src_addr[i0] = cpuif_req_masked & (cpuif_addr == 8'hd4 + (8)'(i0) * 8'h4);
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.length[i0] = cpuif_req_masked & (cpuif_addr == 8'hd8 + (8)'(i0) * 8'h4);
        end
        for(int i0=0; i0<1; i0++) begin
            for(int i1=0; i1<1; i1++) begin
                decoded_reg_strb.dim[i0].dst_stride[i1] = cpuif_req_masked & (cpuif_addr == 8'he0 + (8)'(i0) * 8'hc + (8)'(i1) * 8'h4);
            end
            for(int i1=0; i1<1; i1++) begin
                decoded_reg_strb.dim[i0].src_stride[i1] = cpuif_req_masked & (cpuif_addr == 8'he4 + (8)'(i0) * 8'hc + (8)'(i1) * 8'h4);
            end
            for(int i1=0; i1<1; i1++) begin
                decoded_reg_strb.dim[i0].reps[i1] = cpuif_req_masked & (cpuif_addr == 8'he8 + (8)'(i0) * 8'hc + (8)'(i1) * 8'h4);
            end
        end
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } decouple_aw;
            struct {
                logic next;
                logic load_next;
            } decouple_rw;
            struct {
                logic next;
                logic load_next;
            } src_reduce_len;
            struct {
                logic next;
                logic load_next;
            } dst_reduce_len;
            struct {
                logic [2:0] next;
                logic load_next;
            } src_max_llen;
            struct {
                logic [2:0] next;
                logic load_next;
            } dst_max_llen;
            struct {
                logic next;
                logic load_next;
            } enable_nd;
            struct {
                logic [2:0] next;
                logic load_next;
            } src_protocol;
            struct {
                logic [2:0] next;
                logic load_next;
            } dst_protocol;
        } conf;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } dst_addr;
        } dst_addr[1];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } src_addr;
        } src_addr[1];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } length;
        } length[1];
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } dst_stride;
            } dst_stride[1];
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } src_stride;
            } src_stride[1];
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } reps;
            } reps[1];
        } dim[1];
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } decouple_aw;
            struct {
                logic value;
            } decouple_rw;
            struct {
                logic value;
            } src_reduce_len;
            struct {
                logic value;
            } dst_reduce_len;
            struct {
                logic [2:0] value;
            } src_max_llen;
            struct {
                logic [2:0] value;
            } dst_max_llen;
            struct {
                logic value;
            } enable_nd;
            struct {
                logic [2:0] value;
            } src_protocol;
            struct {
                logic [2:0] value;
            } dst_protocol;
        } conf;
        struct {
            struct {
                logic [31:0] value;
            } dst_addr;
        } dst_addr[1];
        struct {
            struct {
                logic [31:0] value;
            } src_addr;
        } src_addr[1];
        struct {
            struct {
                logic [31:0] value;
            } length;
        } length[1];
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } dst_stride;
            } dst_stride[1];
            struct {
                struct {
                    logic [31:0] value;
                } src_stride;
            } src_stride[1];
            struct {
                struct {
                    logic [31:0] value;
                } reps;
            } reps[1];
        } dim[1];
    } field_storage_t;
    field_storage_t field_storage;

    // Field: idma_reg.conf.decouple_aw
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.decouple_aw.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.decouple_aw.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.decouple_aw.next;
            load_next_c = '1;
        end
        field_combo.conf.decouple_aw.next = next_c;
        field_combo.conf.decouple_aw.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.decouple_aw.value <= 1'h0;
        end else begin
            if(field_combo.conf.decouple_aw.load_next) begin
                field_storage.conf.decouple_aw.value <= field_combo.conf.decouple_aw.next;
            end
        end
    end
    assign hwif_out.conf.decouple_aw.value = field_storage.conf.decouple_aw.value;
    // Field: idma_reg.conf.decouple_rw
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.decouple_rw.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.decouple_rw.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.decouple_rw.next;
            load_next_c = '1;
        end
        field_combo.conf.decouple_rw.next = next_c;
        field_combo.conf.decouple_rw.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.decouple_rw.value <= 1'h0;
        end else begin
            if(field_combo.conf.decouple_rw.load_next) begin
                field_storage.conf.decouple_rw.value <= field_combo.conf.decouple_rw.next;
            end
        end
    end
    assign hwif_out.conf.decouple_rw.value = field_storage.conf.decouple_rw.value;
    // Field: idma_reg.conf.src_reduce_len
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.src_reduce_len.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.src_reduce_len.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.src_reduce_len.next;
            load_next_c = '1;
        end
        field_combo.conf.src_reduce_len.next = next_c;
        field_combo.conf.src_reduce_len.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.src_reduce_len.value <= 1'h0;
        end else begin
            if(field_combo.conf.src_reduce_len.load_next) begin
                field_storage.conf.src_reduce_len.value <= field_combo.conf.src_reduce_len.next;
            end
        end
    end
    assign hwif_out.conf.src_reduce_len.value = field_storage.conf.src_reduce_len.value;
    // Field: idma_reg.conf.dst_reduce_len
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.dst_reduce_len.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.dst_reduce_len.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.dst_reduce_len.next;
            load_next_c = '1;
        end
        field_combo.conf.dst_reduce_len.next = next_c;
        field_combo.conf.dst_reduce_len.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.dst_reduce_len.value <= 1'h0;
        end else begin
            if(field_combo.conf.dst_reduce_len.load_next) begin
                field_storage.conf.dst_reduce_len.value <= field_combo.conf.dst_reduce_len.next;
            end
        end
    end
    assign hwif_out.conf.dst_reduce_len.value = field_storage.conf.dst_reduce_len.value;
    // Field: idma_reg.conf.src_max_llen
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.src_max_llen.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.src_max_llen.value & ~decoded_wr_biten[6:4]) | (decoded_wr_data[6:4] & decoded_wr_biten[6:4]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.src_max_llen.next;
            load_next_c = '1;
        end
        field_combo.conf.src_max_llen.next = next_c;
        field_combo.conf.src_max_llen.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.src_max_llen.value <= 3'h0;
        end else begin
            if(field_combo.conf.src_max_llen.load_next) begin
                field_storage.conf.src_max_llen.value <= field_combo.conf.src_max_llen.next;
            end
        end
    end
    assign hwif_out.conf.src_max_llen.value = field_storage.conf.src_max_llen.value;
    // Field: idma_reg.conf.dst_max_llen
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.dst_max_llen.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.dst_max_llen.value & ~decoded_wr_biten[9:7]) | (decoded_wr_data[9:7] & decoded_wr_biten[9:7]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.dst_max_llen.next;
            load_next_c = '1;
        end
        field_combo.conf.dst_max_llen.next = next_c;
        field_combo.conf.dst_max_llen.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.dst_max_llen.value <= 3'h0;
        end else begin
            if(field_combo.conf.dst_max_llen.load_next) begin
                field_storage.conf.dst_max_llen.value <= field_combo.conf.dst_max_llen.next;
            end
        end
    end
    assign hwif_out.conf.dst_max_llen.value = field_storage.conf.dst_max_llen.value;
    // Field: idma_reg.conf.enable_nd
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.enable_nd.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.enable_nd.value & ~decoded_wr_biten[10:10]) | (decoded_wr_data[10:10] & decoded_wr_biten[10:10]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.enable_nd.next;
            load_next_c = '1;
        end
        field_combo.conf.enable_nd.next = next_c;
        field_combo.conf.enable_nd.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.enable_nd.value <= 1'h0;
        end else begin
            if(field_combo.conf.enable_nd.load_next) begin
                field_storage.conf.enable_nd.value <= field_combo.conf.enable_nd.next;
            end
        end
    end
    assign hwif_out.conf.enable_nd.value = field_storage.conf.enable_nd.value;
    // Field: idma_reg.conf.src_protocol
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.src_protocol.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.src_protocol.value & ~decoded_wr_biten[13:11]) | (decoded_wr_data[13:11] & decoded_wr_biten[13:11]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.src_protocol.next;
            load_next_c = '1;
        end
        field_combo.conf.src_protocol.next = next_c;
        field_combo.conf.src_protocol.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.src_protocol.value <= 3'h0;
        end else begin
            if(field_combo.conf.src_protocol.load_next) begin
                field_storage.conf.src_protocol.value <= field_combo.conf.src_protocol.next;
            end
        end
    end
    assign hwif_out.conf.src_protocol.value = field_storage.conf.src_protocol.value;
    // Field: idma_reg.conf.dst_protocol
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.conf.dst_protocol.value;
        load_next_c = '0;
        if(decoded_reg_strb.conf && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.conf.dst_protocol.value & ~decoded_wr_biten[16:14]) | (decoded_wr_data[16:14] & decoded_wr_biten[16:14]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.conf.dst_protocol.next;
            load_next_c = '1;
        end
        field_combo.conf.dst_protocol.next = next_c;
        field_combo.conf.dst_protocol.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.conf.dst_protocol.value <= 3'h0;
        end else begin
            if(field_combo.conf.dst_protocol.load_next) begin
                field_storage.conf.dst_protocol.value <= field_combo.conf.dst_protocol.next;
            end
        end
    end
    assign hwif_out.conf.dst_protocol.value = field_storage.conf.dst_protocol.value;
    for(genvar i0=0; i0<16; i0++) begin

        assign hwif_out.status[i0].req = decoded_reg_strb.status[i0];
        assign hwif_out.status[i0].req_is_wr = decoded_req_is_wr;
        assign hwif_out.status[i0].wr_data = decoded_wr_data;
        assign hwif_out.status[i0].wr_biten = decoded_wr_biten;
    end
    for(genvar i0=0; i0<16; i0++) begin

        assign hwif_out.next_id[i0].req = decoded_reg_strb.next_id[i0];
        assign hwif_out.next_id[i0].req_is_wr = decoded_req_is_wr;
        assign hwif_out.next_id[i0].wr_data = decoded_wr_data;
        assign hwif_out.next_id[i0].wr_biten = decoded_wr_biten;
    end
    for(genvar i0=0; i0<16; i0++) begin

        assign hwif_out.done_id[i0].req = decoded_reg_strb.done_id[i0];
        assign hwif_out.done_id[i0].req_is_wr = decoded_req_is_wr;
        assign hwif_out.done_id[i0].wr_data = decoded_wr_data;
        assign hwif_out.done_id[i0].wr_biten = decoded_wr_biten;
    end
    for(genvar i0=0; i0<1; i0++) begin
        // Field: idma_reg.dst_addr[].dst_addr
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.dst_addr[i0].dst_addr.value;
            load_next_c = '0;
            if(decoded_reg_strb.dst_addr[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.dst_addr[i0].dst_addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end else begin // HW Write
                next_c = hwif_in.dst_addr[i0].dst_addr.next;
                load_next_c = '1;
            end
            field_combo.dst_addr[i0].dst_addr.next = next_c;
            field_combo.dst_addr[i0].dst_addr.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.dst_addr[i0].dst_addr.value <= 32'h0;
            end else begin
                if(field_combo.dst_addr[i0].dst_addr.load_next) begin
                    field_storage.dst_addr[i0].dst_addr.value <= field_combo.dst_addr[i0].dst_addr.next;
                end
            end
        end
        assign hwif_out.dst_addr[i0].dst_addr.value = field_storage.dst_addr[i0].dst_addr.value;
    end
    for(genvar i0=0; i0<1; i0++) begin
        // Field: idma_reg.src_addr[].src_addr
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.src_addr[i0].src_addr.value;
            load_next_c = '0;
            if(decoded_reg_strb.src_addr[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.src_addr[i0].src_addr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end else begin // HW Write
                next_c = hwif_in.src_addr[i0].src_addr.next;
                load_next_c = '1;
            end
            field_combo.src_addr[i0].src_addr.next = next_c;
            field_combo.src_addr[i0].src_addr.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.src_addr[i0].src_addr.value <= 32'h0;
            end else begin
                if(field_combo.src_addr[i0].src_addr.load_next) begin
                    field_storage.src_addr[i0].src_addr.value <= field_combo.src_addr[i0].src_addr.next;
                end
            end
        end
        assign hwif_out.src_addr[i0].src_addr.value = field_storage.src_addr[i0].src_addr.value;
    end
    for(genvar i0=0; i0<1; i0++) begin
        // Field: idma_reg.length[].length
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.length[i0].length.value;
            load_next_c = '0;
            if(decoded_reg_strb.length[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.length[i0].length.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end else begin // HW Write
                next_c = hwif_in.length[i0].length.next;
                load_next_c = '1;
            end
            field_combo.length[i0].length.next = next_c;
            field_combo.length[i0].length.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.length[i0].length.value <= 32'h0;
            end else begin
                if(field_combo.length[i0].length.load_next) begin
                    field_storage.length[i0].length.value <= field_combo.length[i0].length.next;
                end
            end
        end
        assign hwif_out.length[i0].length.value = field_storage.length[i0].length.value;
    end
    for(genvar i0=0; i0<1; i0++) begin
        for(genvar i1=0; i1<1; i1++) begin
            // Field: idma_reg.dim[].dst_stride[].dst_stride
            always_comb begin
                automatic logic [31:0] next_c;
                automatic logic load_next_c;
                next_c = field_storage.dim[i0].dst_stride[i1].dst_stride.value;
                load_next_c = '0;
                if(decoded_reg_strb.dim[i0].dst_stride[i1] && decoded_req_is_wr) begin // SW write
                    next_c = (field_storage.dim[i0].dst_stride[i1].dst_stride.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                    load_next_c = '1;
                end else begin // HW Write
                    next_c = hwif_in.dim[i0].dst_stride[i1].dst_stride.next;
                    load_next_c = '1;
                end
                field_combo.dim[i0].dst_stride[i1].dst_stride.next = next_c;
                field_combo.dim[i0].dst_stride[i1].dst_stride.load_next = load_next_c;
            end
            always_ff @(posedge clk or negedge arst_n) begin
                if(~arst_n) begin
                    field_storage.dim[i0].dst_stride[i1].dst_stride.value <= 32'h0;
                end else begin
                    if(field_combo.dim[i0].dst_stride[i1].dst_stride.load_next) begin
                        field_storage.dim[i0].dst_stride[i1].dst_stride.value <= field_combo.dim[i0].dst_stride[i1].dst_stride.next;
                    end
                end
            end
            assign hwif_out.dim[i0].dst_stride[i1].dst_stride.value = field_storage.dim[i0].dst_stride[i1].dst_stride.value;
        end
        for(genvar i1=0; i1<1; i1++) begin
            // Field: idma_reg.dim[].src_stride[].src_stride
            always_comb begin
                automatic logic [31:0] next_c;
                automatic logic load_next_c;
                next_c = field_storage.dim[i0].src_stride[i1].src_stride.value;
                load_next_c = '0;
                if(decoded_reg_strb.dim[i0].src_stride[i1] && decoded_req_is_wr) begin // SW write
                    next_c = (field_storage.dim[i0].src_stride[i1].src_stride.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                    load_next_c = '1;
                end else begin // HW Write
                    next_c = hwif_in.dim[i0].src_stride[i1].src_stride.next;
                    load_next_c = '1;
                end
                field_combo.dim[i0].src_stride[i1].src_stride.next = next_c;
                field_combo.dim[i0].src_stride[i1].src_stride.load_next = load_next_c;
            end
            always_ff @(posedge clk or negedge arst_n) begin
                if(~arst_n) begin
                    field_storage.dim[i0].src_stride[i1].src_stride.value <= 32'h0;
                end else begin
                    if(field_combo.dim[i0].src_stride[i1].src_stride.load_next) begin
                        field_storage.dim[i0].src_stride[i1].src_stride.value <= field_combo.dim[i0].src_stride[i1].src_stride.next;
                    end
                end
            end
            assign hwif_out.dim[i0].src_stride[i1].src_stride.value = field_storage.dim[i0].src_stride[i1].src_stride.value;
        end
        for(genvar i1=0; i1<1; i1++) begin
            // Field: idma_reg.dim[].reps[].reps
            always_comb begin
                automatic logic [31:0] next_c;
                automatic logic load_next_c;
                next_c = field_storage.dim[i0].reps[i1].reps.value;
                load_next_c = '0;
                if(decoded_reg_strb.dim[i0].reps[i1] && decoded_req_is_wr) begin // SW write
                    next_c = (field_storage.dim[i0].reps[i1].reps.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                    load_next_c = '1;
                end else begin // HW Write
                    next_c = hwif_in.dim[i0].reps[i1].reps.next;
                    load_next_c = '1;
                end
                field_combo.dim[i0].reps[i1].reps.next = next_c;
                field_combo.dim[i0].reps[i1].reps.load_next = load_next_c;
            end
            always_ff @(posedge clk or negedge arst_n) begin
                if(~arst_n) begin
                    field_storage.dim[i0].reps[i1].reps.value <= 32'h0;
                end else begin
                    if(field_combo.dim[i0].reps[i1].reps.load_next) begin
                        field_storage.dim[i0].reps[i1].reps.value <= field_combo.dim[i0].reps[i1].reps.next;
                    end
                end
            end
            assign hwif_out.dim[i0].reps[i1].reps.value = field_storage.dim[i0].reps[i1].reps.value;
        end
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        for(int i0=0; i0<16; i0++) begin
            wr_ack |= hwif_in.status[i0].wr_ack;
        end
        for(int i0=0; i0<16; i0++) begin
            wr_ack |= hwif_in.next_id[i0].wr_ack;
        end
        for(int i0=0; i0<16; i0++) begin
            wr_ack |= hwif_in.done_id[i0].wr_ack;
        end
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        for(int i0=0; i0<16; i0++) begin
            rd_ack |= hwif_in.status[i0].rd_ack;
        end
        for(int i0=0; i0<16; i0++) begin
            rd_ack |= hwif_in.next_id[i0].rd_ack;
        end
        for(int i0=0; i0<16; i0++) begin
            rd_ack |= hwif_in.done_id[i0].rd_ack;
        end
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[55];
    assign readback_array[0][0:0] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.decouple_aw.value : '0;
    assign readback_array[0][1:1] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.decouple_rw.value : '0;
    assign readback_array[0][2:2] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.src_reduce_len.value : '0;
    assign readback_array[0][3:3] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.dst_reduce_len.value : '0;
    assign readback_array[0][6:4] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.src_max_llen.value : '0;
    assign readback_array[0][9:7] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.dst_max_llen.value : '0;
    assign readback_array[0][10:10] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.enable_nd.value : '0;
    assign readback_array[0][13:11] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.src_protocol.value : '0;
    assign readback_array[0][16:14] = (decoded_reg_strb.conf && !decoded_req_is_wr) ? field_storage.conf.dst_protocol.value : '0;
    assign readback_array[0][31:17] = '0;
    for(genvar i0=0; i0<16; i0++) begin
        assign readback_array[i0 * 1 + 1] = hwif_in.status[i0].rd_ack ? hwif_in.status[i0].rd_data : '0;
    end
    for(genvar i0=0; i0<16; i0++) begin
        assign readback_array[i0 * 1 + 17] = hwif_in.next_id[i0].rd_ack ? hwif_in.next_id[i0].rd_data : '0;
    end
    for(genvar i0=0; i0<16; i0++) begin
        assign readback_array[i0 * 1 + 33] = hwif_in.done_id[i0].rd_ack ? hwif_in.done_id[i0].rd_data : '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 49][31:0] = (decoded_reg_strb.dst_addr[i0] && !decoded_req_is_wr) ? field_storage.dst_addr[i0].dst_addr.value : '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 50][31:0] = (decoded_reg_strb.src_addr[i0] && !decoded_req_is_wr) ? field_storage.src_addr[i0].src_addr.value : '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 51][31:0] = (decoded_reg_strb.length[i0] && !decoded_req_is_wr) ? field_storage.length[i0].length.value : '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        for(genvar i1=0; i1<1; i1++) begin
            assign readback_array[i0 * 3 + i1 * 1 + 52][31:0] = (decoded_reg_strb.dim[i0].dst_stride[i1] && !decoded_req_is_wr) ? field_storage.dim[i0].dst_stride[i1].dst_stride.value : '0;
        end
        for(genvar i1=0; i1<1; i1++) begin
            assign readback_array[i0 * 3 + i1 * 1 + 53][31:0] = (decoded_reg_strb.dim[i0].src_stride[i1] && !decoded_req_is_wr) ? field_storage.dim[i0].src_stride[i1].src_stride.value : '0;
        end
        for(genvar i1=0; i1<1; i1++) begin
            assign readback_array[i0 * 3 + i1 * 1 + 54][31:0] = (decoded_reg_strb.dim[i0].reps[i1] && !decoded_req_is_wr) ? field_storage.dim[i0].reps[i1].reps.value : '0;
        end
    end

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<55; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
