// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package idma_reg_apb_pkg;

    localparam IDMA_REG_APB_DATA_WIDTH = 32;
    localparam IDMA_REG_APB_MIN_ADDR_WIDTH = 8;
    localparam IDMA_REG_APB_SIZE = 'hec;
    localparam SysAddrWidth = 'h20;
    localparam NumDims = 'h2;
    localparam Log2NumDims = 'h0;
    localparam NumProtBits = 'h3;

    typedef struct packed {
        logic [21:0] _reserved_31_10;
        logic [9:0] busy;
    } idma_reg__status__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        idma_reg__status__external__fields__in_t rd_data;
    } idma_reg__status__external__in_t;

    typedef struct packed {
        logic [31:0] next_id;
    } idma_reg__next_id__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        idma_reg__next_id__external__fields__in_t rd_data;
    } idma_reg__next_id__external__in_t;

    typedef struct packed {
        logic [31:0] done_id;
    } idma_reg__done_id__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        idma_reg__done_id__external__fields__in_t rd_data;
    } idma_reg__done_id__external__in_t;

    typedef struct {
        idma_reg__status__external__in_t status[16];
        idma_reg__next_id__external__in_t next_id[16];
        idma_reg__done_id__external__in_t done_id[16];
    } idma_reg__in_t;

    typedef struct {
        logic value;
    } idma_reg__conf__decouple_aw__out_t;

    typedef struct {
        logic value;
    } idma_reg__conf__decouple_rw__out_t;

    typedef struct {
        logic value;
    } idma_reg__conf__src_reduce_len__out_t;

    typedef struct {
        logic value;
    } idma_reg__conf__dst_reduce_len__out_t;

    typedef struct {
        logic [2:0] value;
    } idma_reg__conf__src_max_llen__out_t;

    typedef struct {
        logic [2:0] value;
    } idma_reg__conf__dst_max_llen__out_t;

    typedef struct {
        logic value;
    } idma_reg__conf__enable_nd__out_t;

    typedef struct {
        logic [2:0] value;
    } idma_reg__conf__src_protocol__out_t;

    typedef struct {
        logic [2:0] value;
    } idma_reg__conf__dst_protocol__out_t;

    typedef struct {
        idma_reg__conf__decouple_aw__out_t decouple_aw;
        idma_reg__conf__decouple_rw__out_t decouple_rw;
        idma_reg__conf__src_reduce_len__out_t src_reduce_len;
        idma_reg__conf__dst_reduce_len__out_t dst_reduce_len;
        idma_reg__conf__src_max_llen__out_t src_max_llen;
        idma_reg__conf__dst_max_llen__out_t dst_max_llen;
        idma_reg__conf__enable_nd__out_t enable_nd;
        idma_reg__conf__src_protocol__out_t src_protocol;
        idma_reg__conf__dst_protocol__out_t dst_protocol;
    } idma_reg__conf__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } idma_reg__status__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } idma_reg__next_id__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } idma_reg__done_id__external__out_t;

    typedef struct {
        logic [31:0] value;
    } idma_reg__dst_addr__dst_addr__out_t;

    typedef struct {
        idma_reg__dst_addr__dst_addr__out_t dst_addr;
    } idma_reg__dst_addr__out_t;

    typedef struct {
        logic [31:0] value;
    } idma_reg__src_addr__src_addr__out_t;

    typedef struct {
        idma_reg__src_addr__src_addr__out_t src_addr;
    } idma_reg__src_addr__out_t;

    typedef struct {
        logic [31:0] value;
    } idma_reg__length__length__out_t;

    typedef struct {
        idma_reg__length__length__out_t length;
    } idma_reg__length__out_t;

    typedef struct {
        logic [31:0] value;
    } idma_reg__dst_stride__dst_stride__out_t;

    typedef struct {
        idma_reg__dst_stride__dst_stride__out_t dst_stride;
    } idma_reg__dst_stride__out_t;

    typedef struct {
        logic [31:0] value;
    } idma_reg__src_stride__src_stride__out_t;

    typedef struct {
        idma_reg__src_stride__src_stride__out_t src_stride;
    } idma_reg__src_stride__out_t;

    typedef struct {
        logic [31:0] value;
    } idma_reg__reps__reps__out_t;

    typedef struct {
        idma_reg__reps__reps__out_t reps;
    } idma_reg__reps__out_t;

    typedef struct {
        idma_reg__dst_stride__out_t dst_stride[1];
        idma_reg__src_stride__out_t src_stride[1];
        idma_reg__reps__out_t reps[1];
    } idma_reg__dim__out_t;

    typedef struct {
        idma_reg__conf__out_t conf;
        idma_reg__status__external__out_t status[16];
        idma_reg__next_id__external__out_t next_id[16];
        idma_reg__done_id__external__out_t done_id[16];
        idma_reg__dst_addr__out_t dst_addr[1];
        idma_reg__src_addr__out_t src_addr[1];
        idma_reg__length__out_t length[1];
        idma_reg__dim__out_t dim[1];
    } idma_reg__out_t;
endpackage
